### ISSUE TITLE
Progate Git

### ISSUE THREAD

**Issue by ReiRyuSTI** [Study-FrontEnd-STI/study-git#1]
## Progate 勉強用のTodo
- [x] Gitコース

## できるかどうかの確認
- [x] clone
- [x] pull
- [x] fetch
- [x] merge
- [x] branch
- [x] PR
- [x] リポジトリ―を作ってみる

**Comment by Momi4056** [comment]
●使ったコマンド
履歴
```
history
```
ファイル確認
```
ls
```
ディレクトリーに入る
```
cd
```

**Comment by ReiRyuSTI** [comment]
@Momi4056 
https://backlog.com/ja/git-tutorial/stepup/06/
